### ISSUE TITLE
[BUG] "Delete posts" is not working as expected ?

### ISSUE THREAD

**Issue by KHannibal** [claudiobizzotto/delete-linkedin-activity#2]
Hi @claudiobizzotto and thanks for writing such useful scripts ! 👍 

Unfortunately, one of them (delete posts) is not working as expected. I am using Brave (last version) and this is what I see in the console when running the script.

<img width="584" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3843004/129161359-30f176f5-d7ce-4cc9-8d02-fc064528dd06.png">

However, none of the posts are being deleted. The console displays one warning and one error.

<img width="583" alt="Screenshot 2" src="https://user-images.githubusercontent.com/3843004/129161460-45987c43-7061-4443-a9d7-881319c83d48.png">

<img width="583" alt="Screenshot 3" src="https://user-images.githubusercontent.com/3843004/129161472-605c717a-82d6-41b4-a869-ed9d7bdb45a4.png">

Do you have any idea what is going on ?

Best regards

**Comment by claudiobizzotto** [comment]
Thanks for the details, @KHannibal. I'm going to have a look at this soon.

**Comment by theodorekall** [comment]
Same issue here. I tried with Brave and Firefox. The script goes through the motions but nothing actually gets deleted. 
Love the idea though. I hope you're able to fix this :)

**Comment by nejdetckenobi** [comment]
Same thing here. I tried with Firefox. Also deleting comments are not working. I wish I could help you. What you're trying to provide is awesome.

**Comment by paxperscientiam** [comment]
Deleting posts is addressed in PR #3 :)

**Comment by claudiobizzotto** [comment]
Thanks for PR #3, @paxperscientiam. I'm closing this issue for now, in the hope that the updated script will work across all major browsers (I couldn't test for that yet).
